GET http://localhost:9437/test

####

#runSocialNetwork
POST http://localhost:9437/socialNetwork/run
Content-Type: application/json

{
  "gridLength": 100,
  "population": 100,
  "rounds": 10000,
  "recomType": 2
}

